# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.0.2
_src_path: gh:epics-containers/ioc-template
description: The Generic IOC for the Lakeshore 340 temperature controller
git_platform: github.com
github_org: aardalath
name: ioc-lakeshore340
repo_uri: git@github.com:aardalath/ioc-lakeshore340.git
rtems: false
